---
- name: Setup nginx for the application
  hosts: app
  become: true
  become_user: root
  gather_facts: False
  vars_files:
    - "vars/main.yml"
  tasks:
    - name: copy nginx virtual host file
      template: src="templates/{{env}}-nginx-config.j2"
                dest="/etc/nginx/sites-available/02_app"
                owner=root
                group=root

    - name: link nginx virtual host file
      file: src="/etc/nginx/sites-available/02_app"
            dest="/etc/nginx/sites-enabled/02_app"
            state=link

    - name: restart nginx
      service: name=nginx state=restarted
